// {
//     id: 1,
//     bgColor: '#ADADAD',
//     fontColor: '#000000',
//     executive_posture: 'The gray pose focuses mainly on size.',
//     reps_sets: '12 REPS X 3 SETS',
//     break_period: 'Rest 60 seconds / Set',
//   },
//   {
//     id: 2,
//     bgColor: '#FFFFFF',
//     fontColor: '#000000',
//     executive_posture: 'White posture emphasizes stamina and size.',
//     reps_sets: '20 REPS X 3 SETS',
//     break_period: 'Rest 30 seconds / Set',
//   },
//  bgColor: '#67F55F',
//     fontColor: '#FFFFFF',
//   executive_posture: 'Green posture is a stretching.',
//     reps_sets: '40 seconds x 2 SETS',
//     break_period: 'Rest 20 seconds / Set',

//  bgColor: '#800080',
//     fontColor: '#FFFFFF',
//   executive_posture: 'The purple pose is a hold position.',
//     reps_sets: '30 seconds x 2 SETS',
//     break_period: 'Rest 20 seconds / Set',

//Create Exercise Posture "Full Body"
const res = await ExercisePosture.bulkCreate([
  // White
  {
    name: 'JUMPING JACKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/2W4ZNSwoW_4?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'HIGH STEPPING',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/Cmxr9xcNhgU?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'DEAD BUG',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/bXMQkRowNk8?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'SIDE HOP',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/nYmUEJIBj3c?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'INCHWORMS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/ZY2ji_Ho0dA?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'PLANK LEG UP',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/O9j5_BriCW4?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'BIRD DOG',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/v0oCYe8__bU?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'LUNGE KNEE HOPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/NSy3QKsZ7uI?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'SKATER JUMP',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/5gtLC5BgN7Q?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'QUICK FEET',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/fz59j4a3QMQ?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'SIDE STEP JACKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/p75NmUtH9so?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'CROSS TOUCH AND REACH',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/tTrk6Kzo2OA?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'RUN ON THE WALL',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/Vvuj9R-w6a4?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'ARM SWINGS WITH LATERAL STEPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/tLEkdDgTDbM?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'STAR JUMPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/VVEO_J1tIXU?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },

  {
    name: 'REVERSE CRUNCHES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/UwRfRN5fYRg?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'ABDOMINAL CRUNCHES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/RUNrHkbP4Pc?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'LONG ARM CRUNCHES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/GxKoSEkmRC8?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'RUSSIAN TWIST',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/DJQGX2J4IVw?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'SIDE PLANK',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/2W96p2PIoPg?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'FLUTTER KICKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/K5wuM_gNWyw?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'HEEL TOUCH',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/9bR-elyolBQ?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'STANDING BICYCLE CRUNCHES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/8lsAXzvVHrc?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'BENT LEG TWIST',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/chWR8vsuamo?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'COBRAS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/q46qN4ypiFo?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'HEELS TO THE HEAVENS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/wdS2U6z0JGY?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },

  {
    name: 'INCLINE PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/3WUUeM07i_Q?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'KNEE PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/jWxvty2KROs?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'BOX PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/dcJVA2sBPqw?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'WALL PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/EOf3cGIQpA4?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'REVERSE FLYS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/Cu57U1AqCBk?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'CHEST PRESS PULSE',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/Fz4oo1vFo9M?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'DYNAMIC CHEST',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/kLmWN3Qsj0A?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'DUMBBELL CHEST FLY',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/7uvFOUA4gsY?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'STANDING DUMBBELL CHEST FLY',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/rvpbZiife1I?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'DUMBBELL PULLOVER',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/FCogymf_XK0?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'DUMBBELL DECLINE FLOOR PRESS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/kBDMTp1-iTw?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'DUMBBELL CLOSE GRIP BENCH PRESS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/kQoVg8dUB6Y?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },

  {
    name: 'TRICEPS DIPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/JhX1nBnirNw?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'ARM CIRCLES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/h6GkzSA5tTc?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'ARM RAISES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/Bqvmyni_sKQ?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'SIDE ARM RAISE',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/YslHgg2E-Ro?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'PRONE TRICEPS PUSH UPS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/Rr43jMaoJ9g?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'TRICEPS KICKBACKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/f3E7eEq2c6c?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'REVERSE SNOW ANGELS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/0qLP2RNKX4A?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'FLOOR Y RAISES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/lUGi7NilqWA?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'ARM SCISSORS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/pFrJQ-MyL10?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'PUNCHES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/reeBHtZJ1ts?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'ARM CIRCLES',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/Lha66p0ZXUc?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'SHOULDER GATORS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/JWp8_LGkTR8?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'SHOULDER OUTWARD ROTATION',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/q_uOqXQhBq4?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },

  {
    name: 'SUPERMAN',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/pGeaBXLwDtw?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'BUTT BRIDGE',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/9qo48CYN06w?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'FROGGY GLUTE LIFTS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/wl10q6aqy-4?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'REVERSE FLUTTER KICKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/UsO66ZUvzb0?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'DONKEY KICKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/4ranVQDqlaU?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'FIRE HYDRANT',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/7LnuhLi-78I?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'HIP BRIDGE & LEG LIFT',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/_pDhLWYEC18?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'GLUTE KICK BACK',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/D4gxkgZQkAg?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'SIDE-LYING LEG LIFT',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/VlwBJE1WtOQ?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'STANDING GLUTE KICKBACKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/pn2EZjEE_ZU?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'HIP HINGE',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/VyFDPMOy-eA?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'STANDING GLUTE KICKBACKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/GucHQvB4Bbk?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'BUTT KICKS',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    link: 'https://youtu.be/vXVPvY1UbJI?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },

  //Gray Posture
  {
    name: 'BURPEES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/818SkLAPyKY?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'X-BURPEES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/uD5BUL79CvY?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'MOUNTAIN CLIMBER SQUAT THRUST',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/K0R4snqCbRA?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'MODIFIED BURPEES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/8PbnMQISmZQ?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'JUMPING SQUATS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/txLE-jOCEsc?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'DUMBBELL JUMPING SQUAT',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/WXnXU-KgKVI?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'SPIDERMAN PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/YmonBKorAIw?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },

  {
    name: 'MOUNTAIN CLIMBER',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/wQq3ybaLZeA?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'LEG RAISES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/dGKbTKLnym4?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'SIT-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/swOyWKk7Oko?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'BICYCLE CRUNCHES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/-nJkAJpQemI?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'CROSS ARM CRUNCHES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/Qz3ylqqJ90M?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'V CRUNCH',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/AkHgaJiwtFE?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'CLAPPING CRUNCHES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/LUQt2wSOFNM?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'RECLINED OBLIQUE TWIST',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/XKW5jru5pGo?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'SIDE BRIDGES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/7ytbYd4CK3o?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'V-UP',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/5kvKmRGADlQ?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'DUMBBELL RUSSIAN TWIST',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/FShbaqrGGu4?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'DUMBBELL CRUNCH AND PUNCHES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/j19klieazl0?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },

  {
    name: 'PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/R08gYyypGto?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'DECLINE PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/OjPfLfLsw3c?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'STAGGERED PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/JWNTTiAQMhc?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'HINDU PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/HE0ijmUc6Og?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'REVERSE PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/XRpbVcpx-Yc?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'HOVER PUSH UP',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/6wdVoBSkU0Y?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'WIDE ARM PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/pQUsUHvyoI0?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'DIAMOND PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/UCmqw3kKZ38?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'ONE LEG PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/VSgej87ULzU?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'TIGER BEND PUSH-UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/i-nQPot8ass?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'VALLEY PRESS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/Az3ZkQzc2pU?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },
  {
    name: 'PUSH-UP ROW',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/DpsHmYX3Ifg?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },

  {
    name: 'FLOOR TRICEP DIPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/geNkbcZ6qDo?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'ALTERNATING HOOKS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/wiyvVpEKOsc?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'DOORWAY CURLS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/134v7cB-1W8?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'ARM CURLS CRUNCH',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/pxsOe8MJq68?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'LEG BARBELL CURL',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/3kZS8HVFquk?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'MILITARY PUSH UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/H8LoGZ-ZN48?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'DUMBBELL FRONT RAISE',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/1GG7dkTrBEk?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },

  {
    name: 'SQUATS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/42bFodPahBU?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'SPLIT SQUAT',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/SFSZVKzqnXA?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'PLIE SQUATS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/XEKiRnwBfYA?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'BULGARIAN SPLIT SQUAT',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/Brh1SHAkknI?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'SUMO SQUAT CALF RAISES WITH WALL',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/Hcy81KUTIZ8?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'SUMO SQUAT',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/Z2F0bArQH5s?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'SQUAT PULSES',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/7HarjcM6b10?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'SQUAT REACH UPS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/73Cb-y57UWg?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'IN & OUTS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/clsucWwp5Oc?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'ROUNDHOUSE SQUAT KICKS',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/GfEXIcAaEBM?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },
  {
    name: 'SQUAT THRUST WITH TWIST',
    fontColor: '#000000',
    backgroundColor: '#ADADAD',
    link: 'https://youtu.be/OfwqSK_Ghvk?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },

  // Green postrure
  {
    name: 'CHILD POSE',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/DMwRPGMPB10?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'SIDE-LYING FLOOR STRETCH',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/DMlSdmsHEeI?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'TRUNK ROTATION',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/YBgjuQMviCE?list=PLoVy-85EFtK899UosmFY3vviTqy4s47-q',
    type: 'Full Body',
  },
  {
    name: 'COBRA STRETCH',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/z21McHHOpAg?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'CHEST STRETCH',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/NS64IgKUyeY?list=PLoVy-85EFtK-7EskLPQuB5N6xTlIDLsGJ',
    type: 'Chest',
  },

  {
    name: 'SHOULDER STRETCH',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/9k0EN2RCGgU?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'TRICEPS STRETCH',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/L9IGOcrdcFk?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'STANDING BICEPS STRETCH',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/jw8EXo5h0ec?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'ANTERIOR SHOULDER STRETCH',
    fontColor: '#FFFFFF',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/s8C3OmS82qw?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },

  // Purple posture
  {
    name: 'PLANK',
    fontColor: '#800080',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/Fcbw82ykBvY?list=PLoVy-85EFtK-zlaG-dnlZYfQvB1KfYGGm',
    type: 'Core & Abs',
  },
  {
    name: 'MODIFIED PUSH-UP LOW HOLD',
    fontColor: '#800080',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/fobiVgoeeZA?list=PLoVy-85EFtK-KiUrONIzBciACQgdGFY3Q',
    type: 'Arm',
  },
  {
    name: 'WALL SIT',
    fontColor: '#800080',
    backgroundColor: '#67F55F',
    link: 'https://youtu.be/Yp3ZwACK9v4?list=PLoVy-85EFtK9qMUnjU4yfqfuw2tJzgW3j',
    type: 'Butt',
  },

  //Cardio
  {
    name: 'Low Impact 30 minute cardio workout- Beginner/intermediate',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/50kH47ZztHs?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: 'Beginner/intermediate interval cardio workout - Cardio starter 2!',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/8MImdWV2WfI?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: 'Intermediate Cardio workout',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/wLYeRlyyncY?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: 'Low impact, high intensity cardio and ab workout - at home HIIT fat burning interval exercises',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/g98g7bMQcbc?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: 'Fat burning, high intensity, low impact home cardio workout',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/8oQ-WNJoYtM?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: '25 minute low impact beginner workout - Cardio Motion',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/hdIoPrB_Yfw?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: 'Advanced fat burning HIIT cardio workout - 30 mins.',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/yplP5cLuyf4?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: '30 minute fat burning home workout for beginners. Achievable, low impact results.',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/gC_L9qAHVJ8?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: '25 minute interval cardio workout from home',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/zXK6oXwRr1U?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },
  {
    name: 'Fun 30 minute fat burning HIIT interval cardio workout',
    fontColor: '#FFFFFF',
    backgroundColor: '#F0A500',
    link: 'https://youtu.be/1zPerI8lXs4?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Cardio',
  },

  {
    name: 'Rest',
    fontColor: '#FFFFFF',
    backgroundColor: '#B24080',
    link: 'https://youtu.be/1zPerI8lXs4?list=RDCMUCFjc9H89-RpWuIStDqhO7AQ',
    type: 'Rest',
  },
]);
